Resources:
    Ec2Instance:
        Type: 'AWS::EC2::Instance'
        Properties:
          SecurityGroups:
            - !Ref InstanceSecurityGroup
          KeyName: admin-devops-alemaonull-ubuntu
          ImageId: ami-0d296d66f22f256c2 
    InstanceSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
          GroupDescription: 'Enable SSH access via port 22'
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0


