version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install tar gzip
      - run:
          name: Ensure backend infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name devops-sandbox-stack \
              --region us-east-1
      - run:
          name: Build inventory file
          command: |
            pwd
            echo "[all]" > ~/inventory
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --region us-east-1 \
              --output text >> ~/inventory
            cat ~/inventory

      - persist_to_workspace:
            paths:
              - inventory
          
  print_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/inventory




workflows:
  my_workflow:
    jobs:
      - create_infrastructure
