
version: 2.1

jobs:
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name devops-"${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides NAME=devops-"${CIRCLE_WORKFLOW_ID:0:7}" \
              --region us-east-1  
      - run: aws s3 sync . s3://devops-"${CIRCLE_WORKFLOW_ID:0:7}" --delete


  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID=devops-"${CIRCLE_WORKFLOW_ID:0:7}"

workflows:
  default:
    jobs:
      - create_and_deploy_frontend
      - promote_to_production:
          requires: [create_and_deploy_frontend]

#jobs:
#  create_infrastructure:
#         docker:
#      - image: amazon/aws-cli
#    steps:
#      - checkout
#      - run:
#          name: Ensure backend infrastructure exists
#          command: |
#            aws cloudformation deploy \
#              --template-file template.yml \
#              --stack-name devops-sandbox-stack

#workflows:
#  my_workflow:
#    jobs:
#      - create_infrastructure

