
version: 2.1

jobs:
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
            aws cloudformation deply \
              --template-file bucket.yml \
              --stack-name "${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID}"
      - run: aws s3 sync . s3://"{CIRCLE_WORKFLOW_ID}" --delete


workflows:
  default:
    jobs:
      - create_and_deploy_frontend

#jobs:
#  create_infrastructure:
#         docker:
#      - image: amazon/aws-cli
#    steps:
#      - checkout
#      - run:
#          name: Ensure backend infrastructure exists
#          command: |
#            aws cloudformation deploy \
#              --template-file template.yml \
#              --stack-name devops-sandbox-stack

#workflows:
#  my_workflow:
#    jobs:
#      - create_infrastructure

